#!/bin/sh
set -eu

API_URL="${VITE_API_URL:-}"
AUTH_API_URL="${VITE_AUTH_API_URL:-$API_URL}"
CONFLUENCE_SPACE="${VITE_CONFLUENCE_SPACE:-}"
FILE_CONTENT_MIN_LENGTH="${VITE_FILE_CONTENT_MIN_LENGTH:-20}"
FILE_CONTENT_MAX_LENGTH="${VITE_FILE_CONTENT_MAX_LENGTH:-5000}"
ALLOW_INSECURE_HOSTS="${VITE_ALLOW_INSECURE_HOSTS:-localhost,127.0.0.1}"

cat > /tmp/env.js <<EOF
window.__ENV__ = {
  VITE_API_URL: "${API_URL}",
  VITE_AUTH_API_URL: "${AUTH_API_URL}",
  VITE_CONFLUENCE_SPACE: "${CONFLUENCE_SPACE}",
  VITE_FILE_CONTENT_MIN_LENGTH: "${FILE_CONTENT_MIN_LENGTH}",
  VITE_FILE_CONTENT_MAX_LENGTH: "${FILE_CONTENT_MAX_LENGTH}",
  VITE_ALLOW_INSECURE_HOSTS: "${ALLOW_INSECURE_HOSTS}"
};
EOF
