
services:
  api:
    build: 
      context: ./apps/api
      dockerfile: Dockerfile
    container_name: flowviz-api
    env_file:
      - ./apps/api/.env
    ports:
      - "5001:5001"
    restart: unless-stopped

  backend:
    build: 
      context: .
      dockerfile: ./src/backend/Dockerfile
    container_name: flowviz-backend
    env_file:
      - ./src/backend/.env
    ports:
      - "3001:3001"
    expose:
      - "3001"
    restart: unless-stopped

  frontend:
    build: 
      context: .
      dockerfile: ./src/frontend/Dockerfile
    container_name: flowviz-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
      - api
    restart: unless-stopped